name: check

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  checkAndUpload:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
          
      - name: Get GIT Authority
        run: |
          go env -w GOPRIVATE="github.com/LF112"
          git config --global url."https://LF112:${{ secrets.GIT }}@github.com".insteadOf "https://github.com"
          go get -v -t -d ./...
          git config --global user.email "lf@lf112.net"
          git config --global user.name "LF112"
          
      - name: RUN
        run: node ./autoIndex
        
      - name: Upload
        run: |
          git add . && git commit -m "🚀 AUTO UPLOAD Index"
          git push --set-upstream origin master
